# -*- coding: utf-8 -*-
"""
Created on Fri Oct 24 15:45:25 2025

@author: rbala

Interactive Dashboard for postprocessing
"""
import streamlit as st
from datetime import datetime
import tempfile
from src.postprocessing.dashboard_utils import load_oemof_results, interpret_results, create_bus_dataframes, create_component_dataframes, extract_system_metadata
from src.postprocessing.dashboard_utils import display_bus_analysis, display_component_analysis, display_system_summary
import os

st.set_page_config(
        page_title="Oemof Energy Model Analysis", 
        layout="wide",
        page_icon="🔋"
    )
    
st.title("🔋 Oemof Energy System Dashboard")
st.markdown("Upload your oemof dump file to analyze simulation results")

# File upload section
st.sidebar.header("📁 Data Upload")
uploaded_file = st.sidebar.file_uploader(
    "Choose oemof dump file", 
    type=['dump'],
    help="Upload a .dump file generated by oemof simulation"
)

if uploaded_file is not None:
    try:
        # Display file info
        file_details = {
            "Filename": uploaded_file.name,
            "File size": f"{uploaded_file.size / 1024:.1f} KB",
            "Upload time": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        }
        
        st.sidebar.success("✅ File uploaded successfully!")
        st.sidebar.json(file_details)
        
        # Save uploaded file to temporary file
        with tempfile.NamedTemporaryFile(delete=False, suffix='.dump') as tmp_file:
            tmp_file.write(uploaded_file.getvalue())
            tmp_file_path = tmp_file.name
                
        # Load and process data
        with st.spinner("Loading and processing oemof data..."):
            energysystem, results = load_oemof_results(tmp_file_path)
            
            if energysystem is not None and results is not None:
                # Use the enhanced interpret_results function
                bus_sequences, bus_scalars, component_sequences, component_scalars, component_bus_mapping = interpret_results(results)
                
                # Create DataFrames
                bus_dfs = create_bus_dataframes(bus_sequences, energysystem)
                component_dfs = create_component_dataframes(component_sequences, energysystem)
                
                # Extract metadata
                metadata = extract_system_metadata(energysystem, bus_dfs, component_dfs, component_bus_mapping)
                
                # Clean up temporary file
                os.unlink(tmp_file_path)
                
                # Create tabs for different analyses
                tab1, tab2, tab3 = st.tabs([
                    "Bus Analysis", 
                    "Component Analysis", 
                    "System Overview"
                ])
                
                with tab1:
                    display_bus_analysis(bus_dfs, metadata)
                
                with tab2:
                    display_component_analysis(component_dfs, metadata)
                
                with tab3:
                    display_system_summary(bus_dfs, component_dfs, metadata)
            
            else:
                st.error("Failed to load the oemof dump file. Please check the file format.")
                
    except Exception as e:
        st.error(f"Error processing file: {str(e)}")
        st.info("Please ensure you're uploading a valid oemof dump file (.dump)")

else:
    # Welcome message when no file is uploaded
    st.markdown("""
    ## Welcome to the Oemof Energy System Dashboard!
    
    This dashboard provides:
    
    - **Bus Analysis**: Detailed flow analysis for each energy bus
    - **Component Analysis**: Individual component performance
    - **System Overview**: Comprehensive system metrics and summaries
    
    Upload your oemof dump file to get started!
    """)